version: "3.5"

services:
  latexer:
    image: docker-repository.bv-soft.pl/latexer:latest
    volumes:
      - ../output/:/shared
    environment:
      - FILENAME=bv_invoice
    depends_on:
      - pythoner

  pythoner:
    image: docker-repository.bv-soft.pl/pythoner:latest
    volumes:
      - ../input/:/app/resources
      - ../output/:/shared
    environment:
      - FILENAME=bv_invoice
